##
# @author Guillaume Robin <robinguillaume.pro@gmail.com>
# @file eslint configuration file
# @desc Created on 2020-06-13 7:37:05 pm
# @copyright GNU General Public License v3.0
#
env:
  node: true
  mocha: true
  es6: true
extends: 'eslint:recommended'
rules:
  no-console: 'off'
